name: Sync GitHub issues to Jira
on:
  issues:
    types:
      - opened
      - closed
permissions:
  issues: write
jobs:
  jira:
    uses: acquia/.github/.github/workflows/jira.yml@CLI-1116
    secrets:
      jira-base-url: ${{ secrets.JIRA_BASE_URL }}
      jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
      jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
